### ISSUE TITLE
Public release checklist

### ISSUE THREAD

**Issue by eduardoboucas** [dadi/publish#634]
- [ ] Merge https://github.com/dadi/registry/pull/8 and deploy registry
- [ ] Merge https://github.com/dadi/cli/pull/45 and deploy CLI
- [ ] Merge https://github.com/dadi/docs/pull/125 and deploy docs site
- Release `@dadi/publish`

**Comment by eduardoboucas** [comment]
DONE! 🚀
